global:
  scrape_interval: 10s
  evaluation_interval: 10s
 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus
          
  - job_name: locust
    metrics_path: '/export/prometheus'
    static_configs:
      - targets: ['your_ip:8089']  # 地址修改为实际地址
        labels:
          instance: locust