global:
  scrape_interval: 10s
  evaluation_interval: 10s
 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          instance: prometheus
          
  - job_name: locust
    metrics_path: '/export/prometheus'
    static_configs:
      - targets: ['locust-master:8089']
        labels:
          instance: locust